type User {
	_id: String!
	uniqueName: String!
	name: String!
	avatar: String
	isOwner: Boolean!
	guilds: [UserGuild]!
}

type UserGuild {
	id: String!
	name: String!
	icon: String
	owner: Boolean!
	permissions: Int!
	permissions_new: String!
}

type Query {
	user: User @auth(requires: USER)
}

type Mutation {
	logoutUser: User @auth(requires: USER)
}
